### ISSUE TITLE
Search by page title

### ISSUE THREAD

**Issue by JiriTrecak** [Supernova-Studio/exporter-documentation#11]
### Description

Add the ability to search by page title, in addition to sections and texts, and have it all work together within one search window.

### Acceptance criteria

1. Search can find pages by title
1. Search can find pages by section (header)
1. Search can search through page content
1. Clicking on item takes users to the appropriate page

**Comment by JiriTrecak** [comment]
This is now done, alongside other improvements, see - https://supernova-studio.slack.com/archives/CKNAHL8KG/p1658290158852659

**Comment by illia-ks** [comment]
Changes were requested for AC1 - addressed at #3276

**Comment by JiriTrecak** [comment]
Now searches groups as well, pages are extended and renamed to Pages & Categories

**Comment by illia-ks** [comment]
Tested on DEV - no issues were found. Ready for Staging

**Comment by illia-ks** [comment]
Tested on Staging - no issues were found. Ready for PROD

**Comment by illia-ks** [comment]
Added to RS, can be closed now
