### ISSUE TITLE
Update settings copy

### ISSUE THREAD

**Issue by Ydus** [Supernova-Studio/exporter-documentation#13]
### Description
Continuation of [#3375](https://github.com/Supernova-Studio/supernova-studio-flutter/issues/3375#issuecomment-1191294028)

Update the settings copy to match the latest UX copy guidelines.

### Acceptance criteria
1. All the sections are in `Sentence case`
1. The `Look & feel` section is renamed to `Appearance`

**Comment by JiriTrecak** [comment]
Done

**Comment by illia-ks** [comment]
@JiriTrecak can you please reflect changes here to: https://github.com/Supernova-Studio/exporter-documentation/tree/features/private-repositories. (right now available here: https://github.com/Supernova-Studio/exporter-documentation/tree/master)

I was a bit confused, when I pulled the latest version of exporter on DEV and it was lower then on PROD :) 

Thank you!

**Comment by illia-ks** [comment]
Or just repository url, I don't have access to WS with it, I made a copy with second url as short-term solution, but would avoid mess in the shop :)

**Comment by illia-ks** [comment]
Otherwise tested successfully `Look & Feel` was renamed, all  sections in `Docs` settings are in `Sentence case `

**Comment by illia-ks** [comment]
Tested on Staging - no issues were found. It's ready for PROD

**Comment by illia-ks** [comment]
Tested on PROD - no issues were found. Can be reviewed now.

**Comment by illia-ks** [comment]
Added to RS, can be closed now
