### ISSUE TITLE
Markdown from private repositories

### ISSUE THREAD

**Issue by Ydus** [Supernova-Studio/exporter-documentation#15]
### Description
It must be possible to use the Markdown Block in the Docs editor with URLs to MD files that are in private repos.

### Related resources
User docs ticket: #17

### Acceptance criteria
1. The exporter provides a custom property to provide authentication for markdown block
    1. If a markdown block is configured with a link to a private repository, the authentication is used

**Comment by honzatmn** [comment]
@Ydus @JiriTrecak I believe this is done.

**Comment by honzatmn** [comment]
Resolved in ENG-399
