### ISSUE TITLE
Bug: Trying to render Token Group as Stack results in Docs failing to deploy

### ISSUE THREAD

**Issue by jan-supernova** [Supernova-Studio/exporter-documentation#18]
### Issue
If you try to publish Docs with `Token Group` Block in it with `Render as...` set to `Stack`, you can notice that the Docs deployment fails with:

```
Finished exporting source full_page.pr for documentation page Code
Finished exporting source full_page.pr for documentation page Overview
Export of full_page.pr for documentation page Introduction failed
  | Injected blueprint execution failed
  | Cannot read property 'name' of null
  | Injected blueprint execution failed
  | Cannot read property 'name' of null
  | Injected blueprint execution failed
  | Cannot read property 'name' of null
  | Injected blueprint execution failed
  | Cannot read property 'name' of null
  | Blueprint execution failed
  | Cannot read property 'name' of null
Cannot read property 'name' of null
```

Rendering as `Table` or `Grid` (regardless of how many columns) works properly.

Link to the DS: `https://cloud-dev.supernova.io/ws/company-testing-ws/ds/2222-stack-fail/latest/documentation/editor` - just press `Publish`

### Scenario
Issue can be reproduced following this exact scenario below:

1. Create some Supernova Color tokens in DS.
1. Start editing Docs.
1. Add `Token Group` Block into Docs.
1. Select the relevant group.
1. Right click on `Token Group` block and select `Render as...` -> `Stack`.
1. Publish Docs now.

### Expected result
Docs are properly published when containing Token Group Block set to render as Stack.

### Additional information
Screenshot:

![Screenshot 2022-07-25 at 13.15.41.png](https://images.zenhubusercontent.com/5d13751984dbbd27942b5cd3/73fbc588-ea02-4fce-b563-094dab396646)

Build:

![Screenshot 2022-07-25 at 13.18.17.png](https://images.zenhubusercontent.com/5d13751984dbbd27942b5cd3/58a40ba0-825f-4b23-a02d-c27dd7dd171d)

### Versions used
* Documentation Exporter version 1.48.0
* OS: macOS Monterey 12.4 (21F79).

**Comment by JiriTrecak** [comment]
Work for me @jan-supernova , any additional information?

**Comment by JiriTrecak** [comment]
@jan-supernova This should be re-tested if it still does it. If so, the new debug information should shed more light on it

**Comment by jan-supernova** [comment]
@JiriTrecak retested on https://cloud-dev.supernova.io/ws/company-testing-ws/ds/2222-stack-fail/latest/documentation/editor (you have access too). It doesn’t fail now, but it seems that the build just goes forever:

![Screenshot 2022-09-06 at 10.36.15.png](https://images.zenhubusercontent.com/5d13751984dbbd27942b5cd3/ee081ee3-dd28-4e2c-b423-345d718d7244)

The middle build which went through was with Token Group rendering set as `Table` - this worked. But simply setting it as `Stack` and trying to publish Docs again make you run into this.

**Comment by honzatmn** [comment]
Hey @jan-supernova , is this still happening? We have Stacks [here](https://learn.supernova.io/latest/documentation/types-of-blocks/token/tokens/variants.html#search-2c55dc10-0c1e-11ed-8dd9-cdbf6748f88c), and everything seems to work properly. If it's still there, can you please provide more details how to simulate it?

**Comment by jan-supernova** [comment]
@honzatmn can confirm that it seems to be working properly now. So this can be pushed further. :)

**Comment by jan-supernova** [comment]
Quick Staging check - OK. This is Ready for Prod.

**Comment by jan-supernova** [comment]
Quick Prod check - OK. Moving to Story Review.

**Comment by jan-supernova** [comment]
No need to mention this specific case in RS since it’s covered in other scenarios,This can be closed now.
