### ISSUE TITLE
Block variant thumbnails and descriptions

### ISSUE THREAD

**Issue by Ydus** [Supernova-Studio/exporter-documentation#27]
### Description
Add thumbnails and descriptions to each block variant.

#### UX
- We need the description copy for all the available block variants

#### UI
- We need thumbnail images for all the available block variants

### Related resources
Design
- **TODO**

### Acceptance criteria
1. Each block variant has thumbnail and description

**Comment by honzatmn** [comment]
@Ydus We have this done in Figma, I'll be adding images and descriptions to the exporter too. Can you please advise on how should I structure it in `exporter.json` and where to store image assets? 🙏
