### ISSUE TITLE
Bug: Under certain conditions, paths cause export to fail (Documentation) 

### ISSUE THREAD

**Issue by illia-ks** [Supernova-Studio/exporter-documentation#28]
### Issue

If there're two different components in two separate groups with the same names - it'll lead to the issue with `Docs` publication. 

### Scenario
Issue can be reproduced following this exact scenario below:

**Example**

If you'll have such hierarchy:

```
Components\ 
  Button\ (slug=button)
    Design (slug=design-1)
  Button\ (slug=button-1)
    Design (slug=design-1) 
```

The exporter will produce duplicated urls : /`components/button/design-1.html` instead of `/components/button/design-1.html` and `/components/button-1/design-1.html`, which leads to the problem with publication.

### Expected result

As a user I expect, that I won't face an issue with `Docs` publication, even if I'll have  two different components with the same names in two separate groups.

### Additional information

Slack thread - [click me](https://supernova-studio.slack.com/archives/C01JYKBTYKG/p1660839400125829)

### Versions used
* Up-to-date https://cloud.supernova.io/.
* Documentation exporter version: 2.0.1
* OS: macOS Monterey 12.5 (21G72).

**Comment by JiriTrecak** [comment]
This is definitely not me-ticket, as it is UI work @Ydus, also not exporter. I can fix the incorrect publish of URLs so in this situation it doesn't fail, but the title is indication of different but that I reported

**Comment by Ydus** [comment]
@JiriTrecak if you read the `Example` section, it sounds like an exporter issue

**Comment by JiriTrecak** [comment]
Fixed, deployed on prod as well, please retest that I didn't miss anything but I deployed 10 docs and they seem to work well

**Comment by illia-ks** [comment]
Tested on DEV - no issues were found. (available across all envs)

**Comment by illia-ks** [comment]
Tested on Staging - no issues were found. Ready for PROD

**Comment by illia-ks** [comment]
Tested on PROD - no issues were found. Can be reviewed now.

**Comment by illia-ks** [comment]
Added to RS, can be closed now
