### ISSUE TITLE
Token properties in token blocks

### ISSUE THREAD

**Issue by Ydus** [Supernova-Studio/exporter-documentation#35]
### Description
Right now we are exporting all the custom properties together with each token in token blocks, but this is often excessive amount of data. We have added the option to deselect properties within each token block so they are not shown anymore.

### Acceptance criteria
1. Token blocks are only exporting the selected token properties
    1. Detail
    1. List
    1. Group

**Comment by honzatmn** [comment]
This will be resolved with #65
