### ISSUE TITLE
Bug: If the table is "Fit to the page" on published Docs it's slightly scrollable horizontally 

### ISSUE THREAD

**Issue by illia-ks** [Supernova-Studio/exporter-documentation#36]
### Issue

 If the table is "Fit to the page width" on published Docs it's slightly scrollable horizontally.

### Scenario
Issue can be reproduced following this exact scenario below:

1. Go to https://cloud.supernova.io/
1. Go to `Docs`
1. Create a table
1. Choose `Fit to the page width` (click on `Gear` icon)
1. Publish Docs
1. Click on `View` button

### Expected result

As a user, I expect, that the table will exactly fit the page and won't be scrollable.

### Additional information

https://images.zenhubusercontent.com/360480164/51ff7d4e-5b3e-4301-bb53-349a82e45b9b/table_width.mov

### Versions used
* Documentation Exporter version 2.3.0
* OS: macOS Monterey 12.5 (21G72).

**Comment by illia-ks** [comment]
@JiriTrecak FYI

**Comment by JiriTrecak** [comment]
@illia-ks This should work

**Comment by jan-supernova** [comment]
Tables with `Fit to the page` seem to be published in correct size now. This is OK and Ready for Staging.

**Comment by jan-supernova** [comment]
Quick Staging check - OK. This is Ready for Prod.

**Comment by jan-supernova** [comment]
Quick Prod check - OK. Moving to Story Review.

**Comment by jan-supernova** [comment]
Quick Prod check - OK. Moving to Story Review.

**Comment by jan-supernova** [comment]
Pure regression - no need to add this to RS. This can be closed now.
