### ISSUE TITLE
Bug: Icon missing at Callout block in published Docs (Safari)

### ISSUE THREAD

**Issue by illia-ks** [Supernova-Studio/exporter-documentation#41]
### Issue

Icons are missing at `Callout` blocks in published `Docs`, they are in place in the `Docs` editor. Issue present in Safari only. 

### Scenario
Issue can be reproduced following this exact scenario below:

1. Open Safari
1. Go to https://cloud.supernova.io/
1. Go to `Docs`
1. Add `Callout` block(s)
1. Publish `Docs`
1. Open them

### Expected result

As a user I expect, that the `Callout` blocks will have icons on published version.

### Additional information

![Safari-callout-block.png](https://images.zenhubusercontent.com/62b02a478a9df01fa5545341/86c57eb3-c892-47e6-8d01-b1116e77a0b8)

### Versions used
* Documentation Exporter version 2.3.1
* Browser: Safari Version 15.6 (17613.3.9.1.5).
* OS: macOS Monterey 12.5 (21G72).

**Comment by honzatmn** [comment]
Ready to test here: https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/common-blocks.html

**Comment by illia-ks** [comment]
Tested on DEV - no issues were found. Ready for Staging

**Comment by honzatmn** [comment]
> Tested on DEV - no issues were found. Ready for Staging

We don't have staging for exporters, so I'll just merge it and release it. Wdyt? 🙏

**Comment by JiriTrecak** [comment]
Let's go :)

**Comment by illia-ks** [comment]
@honzatmn sure thing, let me know please, when it's done - I'll move the ticket further :)

**Comment by jan-supernova** [comment]
Looks good to me in Safari - this can go to Story Review.

**Comment by jan-supernova** [comment]
Added to RS. This can be closed now.
