### ISSUE TITLE
Fixes & small UX improvements of the documentation styling

### ISSUE THREAD

**Issue by honzatmn** [Supernova-Studio/exporter-documentation#43]
### Description
A collection of fixes and small improvements for Default Documentation Exporter, usually reported by customers.

### Related resources
Slack discussion: across several channels, also reported by customers

User docs ticket: none

Wireframe
- none

Design
- none

### Acceptance criteria
1. Images now use Caption as alt text. If there is no caption, the `alt` is empty. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/common-blocks.html)
1. It's possible to copy the code with "Copy" button on the code block. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/code.html)
1. If the page has tabs, they stay sticky when the page is scrolled. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/token-group/variant-table.html)
1. Icons in Callout block are now displayed also in Safari. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/common-blocks.html)
1. A font in tables gets boldened the same way as in the editor – header column and row are bold automatically, the other cells only when the text inside is bold. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/tables.html)
1. Spacing in the ordered list is aligned with the other blocks vertically. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/common-blocks.html)
1. Typography tokens have a preview matching the token definition, not a general one. [Test here](https://supernova-docs.supernova-docs.io/testing-grounds/latest/block-kitchen-sink/token-group/variant-grid-4.html)

**Comment by illia-ks** [comment]
Tested 

AC1 - passed
AC2 - passed
AC3 - passed
AC4 - passed
AC5 - passed
AC6 - passed
AC7 - passed

**Comment by illia-ks** [comment]
Tested on PROD, can be reviewed now

**Comment by illia-ks** [comment]
Added to RS, can be closed now
