### ISSUE TITLE
Themes in token blocks

### ISSUE THREAD

**Issue by Ydus** [Supernova-Studio/exporter-documentation#50]
### Description
Token blocks can now optionally include one theme that can be displayed in either override or comparison modes.

### Related resources
Design
- [Default](https://www.figma.com/file/8EkL0eEFLKXxIJ8Nau4lsg/Docs-Default-Exporter-(Nebula)?node-id=2597%3A21426)
- [Responsive](https://www.figma.com/file/8EkL0eEFLKXxIJ8Nau4lsg/Docs-Default-Exporter-(Nebula)?node-id=297%3A8191)

### Acceptance criteria
The following applies to all token block types (detail, list, group)

1. If there is a theme assigned to the block:
    1. If the block is in override mode, the resolved token values are displayed and it is clear if a value is overriden in the theme or not
    1. If the block is in comparison mode, the default and theme value are side by side
1. The above works

1. The tokens blocks are exported and matching the design:
    1. In default mode
    1. In responsive mode

**Comment by Ydus** [comment]
@honzatmn is there any progress on this?

**Comment by honzatmn** [comment]
> @honzatmn is there any progress on this?

Yes, working on implementation right now since the data model was updated yesterday

**Comment by Ydus** [comment]
@honzatmn is there design for this? :thinking: it never moved past the UX stage

**Comment by honzatmn** [comment]
> @honzatmn is there design for this? 🤔 it never moved past the UX stage

Designs for the block were done together with the updates in the token block a few weeks ago, [designs are here](https://www.figma.com/file/8EkL0eEFLKXxIJ8Nau4lsg/Docs-Default-Exporter-(Nebula)?node-id=2680%3A38485)

Note that there is only the Table variant covered, I'll be covering the rest of the variant during implementation.

**Comment by Ydus** [comment]
@honzatmn they are under `(exploration)` which sounds unfinished - are these final? If they are actually finished, can we move then under the normal page? Also I don't see themes in the responsive version anywhere. We need all of these linked here, so it can be properly tested :slightly_smiling_face:

**Comment by Ydus** [comment]
@honzatmn Matěj has added the responsive design and I assume you will be taking of the designs for the variants yourself. I'm moving this to in progress. It would be great if you could link the other designs here when they are done so everything can be tested properly :pray:
