### ISSUE TITLE
Bug: Page Tabs in published Docs overflow the main menu when it is opened in the compact view 

### ISSUE THREAD

**Issue by jan-supernova** [Supernova-Studio/exporter-documentation#54]
### Issue
This is a relatively specific situation - you need to have a published page which contains some page tabs and be on a compact view (< 990 px). Once you are in compact view and click on the hamburger icon `≡`, the main menu appears. However, if you are scrolled on top, you can notice that the page tabs below overflow the menu which is supposed to be above them. See the screenshot:

![Screenshot 2022-10-18 at 17.42.18.png](https://images.zenhubusercontent.com/5d13751984dbbd27942b5cd3/7ddbee1c-c895-4471-a172-894985a01ed9)

### Scenario
Issue can be reproduced following this exact scenario below:

1. Visit any page that contains some page tabs, like `https://learn.supernova.io/latest/design-systems/add-design-system-content/data-sources/overview.html`.
1. Do not scroll; stay on top of the page.
1. Change the browser width until `≡` icon for the main menu appears.
1. Click on the `≡` icon.

### Expected result
When the main menu in compact view is triggered, it overflows page tabs, not the other way around.

### Additional information
Video:

https://images.zenhubusercontent.com/360480164/aa83faac-8ef5-4a32-a2a3-4b7b235ca4cc/screen_recording_2022_10_18_at_17_35_19.mov

### Versions used
* Up-to-date https://cloud.supernova.io/.
* OS: macOS Monterey 12.1 (21C52).

**Comment by honzatmn** [comment]
I believe this was fixed already
