### ISSUE TITLE
Bug: Hidden page is displayed in Shortcuts block

### ISSUE THREAD

**Issue by illia-ks** [Supernova-Studio/exporter-documentation#58]
### Issue

Hidden page is displayed in `Shortcuts` block.

### Scenario
Issue can be reproduced following this exact scenario below:

1. Go to https://cloud-*.supernova.io
1. Go to `Docs` tab
1. Create a `Shortcuts` block
1. Add hidden page there
1. Click on `Publish` button
1. Click on `View` button
1. Investigate the block

### Expected result

As a user I expect, that the hidden page(s) won't be displayed in `Shortcuts` block

### Additional information
![CleanShot 2022-10-26 at 18.09.30.png](https://images.zenhubusercontent.com/62b02a478a9df01fa5545341/42e98ca3-e0bf-4011-9502-e75cfa4e7634)

### Versions used
* Documentation Exporter version 3.0.6
* OS: macOS Monterey 12.4 (21F79).

**Comment by honzatmn** [comment]
This is fixed already.
