### ISSUE TITLE
Bug:  If there’re more, then 6 Figma frames in 1 row - name of the frame doesn’t fit

### ISSUE THREAD

**Issue by illia-ks** [Supernova-Studio/exporter-documentation#61]
### Issue

If there’re more, then 6 Figma frames in 1 row - name of the frame doesn’t fit

### Scenario
Issue can be reproduced following this exact scenario below:

1. Go to https://cloud.supernova.io/
1. Go to Docs
1. Add more then 6 Figma frame blocks in 1 row
1. Publish
1. View

### Expected result

As a user I expect, that the names at Figma block will be displayed properly, no matter how many of them in 1 row. 

### Additional information

![Screenshot 2022-11-03 at 16.03.06.png](https://images.zenhubusercontent.com/62b02a478a9df01fa5545341/4597bd3f-0132-443b-abe7-dca326f3afc1)

### Versions used
* Documentation Exporter version 4.0.0 (Nebula)
* OS: macOS Monterey 12.4 (21F79).

**Comment by honzatmn** [comment]
Resolved in ENG-401
