### ISSUE TITLE
Bug: Deployment of Docs fails if the Shortcut contains a completely empty title

### ISSUE THREAD

**Issue by jan-supernova** [Supernova-Studio/exporter-documentation#64]
### Issue
Deployment of Docs fails if the Shortcut block contains a title which is empty. This can happen if you add a new Shortcut block into the Docs page, assign some different page into it and delete the assigned page from the left menu right away. Once you try to publish Docs like this, their deployment fails. 

Build log:

```
Finished exporting source index_page.pr
Finished exporting source search_index.pr
Finished exporting source sitemap.pr
Export of full_page.pr for documentation page Empty Shortcuts failed
  | Failed processing template node
     - Executed blueprint: "page_block_shortcut.pr"
     - Executed node: [substitution]:  withHTMLNewlines(shortcut.title) 
     - Path: "page_block_shortcut.pr:38:25"
     - Debug symbol: "e4f434c3-fe76-49f7-a345-e53b9d1c127a"
     - Stack: 123 loaded variables
Cannot read property 'split' of null
```

### Scenario
Issue can be reproduced following this exact scenario below:

1. Start editing Docs.
1. Put a `Shortcut` block into Docs.
1. Assign some Docs page as its shortcut.
1. Delete the assigned Docs page from the menu right away.
1. Shortcut title becomes empty.
1. Try to publish Docs.

### Expected result
Docs are published even when the Shortcut title is missing.

### Additional information
Video:

https://images.zenhubusercontent.com/360480164/d700c625-6d87-4181-b2fe-55648d99a428/screen_recording_2022_11_10_at_11_57_40.mov

### Versions used
* Documentation Exporter version 4.0.1
* OS: macOS Monterey 12.4 (21F79).

**Comment by honzatmn** [comment]
Fixed in ENG-400
