### ISSUE TITLE
Bug: `Table` not using `<thead>`

### ISSUE THREAD

**Issue by jcusick93** [Supernova-Studio/exporter-documentation#86]
I noticed that in your block table you are not using a `<thead>` element
<img width="1238" alt="Screen Shot 2023-03-23 at 12 51 33 PM" src="https://user-images.githubusercontent.com/37253884/227277991-b82b7614-617e-463d-aff7-fbea47c88c2a.png">

**Comment by jcusick93** [comment]
Any update on this @JiriTrecak ?

**Comment by honzatmn** [comment]
Hey @jcusick93, the fix was just deployed in the latest version. If you republish your documentation, it should now contain `thead`, `tbody`, and correct `th` tags for specific cells. Thanks for reporting this (and for your patience)!
